// Reproducible browser/isolate parser: plugin-cli only bundles emdash/plugin and zod.
import {build} from "esbuild";
import {readFile,writeFile,mkdir} from "node:fs/promises";
import {dirname,join,resolve} from "node:path";
import {createRequire} from "node:module";
import {fileURLToPath} from "node:url";
const parserEntry=fileURLToPath(import.meta.resolve("htmlparser2"));
const fromParser=createRequire(parserEntry);
const handlerEntry=join(dirname(fromParser.resolve("domhandler")),"esm/index.js");
const parserPath=join(dirname(parserEntry),"Parser.js");
await mkdir("src/vendor",{recursive:true});
const result=await build({stdin:{contents:`import {Parser} from ${JSON.stringify(parserPath)};import {DomHandler} from ${JSON.stringify(handlerEntry)};export function parseDocument(html,options){const handler=new DomHandler(undefined,options);new Parser(handler,options).end(html);return handler.root;}`,resolveDir:process.cwd(),sourcefile:"html-parser-entry.js"},bundle:true,format:"esm",platform:"neutral",target:"es2022",minify:true,metafile:true,outfile:"src/vendor/html-parser.mjs",banner:{js:"// Generated by scripts/vendor-html.mjs; htmlparser2 10.0.0. MIT notices: LICENSES.txt."}});
let notices="Vendored parser dependencies. Generated, do not edit.\n\n";
const directories=new Set();
for(const input of Object.keys(result.metafile.inputs).filter(p=>p.includes('node_modules/'))){let dir=dirname(resolve(input));while(true){try{const p=JSON.parse(await readFile(join(dir,'package.json'),'utf8'));if(p.name){directories.add(dir);break;}}catch{}const parent=dirname(dir);if(parent===dir)throw new Error(`No metadata for ${input}`);dir=parent;}}
for(const dir of directories){
 const pkg=JSON.parse(await readFile(join(dir,"package.json"),"utf8"));
 let license;for(const filename of ["LICENSE","LICENSE.txt"]){try{license=await readFile(join(dir,filename),"utf8");break;}catch{}}
 if(!license)throw new Error(`Missing license: ${pkg.name}`);
 notices+=`${pkg.name} ${pkg.version}\n${license}\n\n`;
}
await writeFile("src/vendor/LICENSES.txt",notices);
