packages:
  - "."

strictDepBuilds: true
dangerouslyAllowAllBuilds: false
allowBuilds:
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - '@emdash-cms/admin@1.0.1 || 1.1.0'
  - '@emdash-cms/auth@1.0.1 || 1.1.0'
  - '@emdash-cms/blocks@1.0.1 || 1.1.0'
  - '@emdash-cms/cloudflare@1.0.1 || 1.1.0'
  - '@emdash-cms/gutenberg-to-portable-text@1.0.1 || 1.1.0'
  - '@emdash-cms/plugin-cli@0.13.1 || 0.13.2'
  - '@emdash-cms/plugin-test@0.2.6 || 0.2.7'
  - emdash@1.0.1 || 1.1.0
