packages:
  - "."

strictDepBuilds: true
dangerouslyAllowAllBuilds: false
allowBuilds:
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - '@emdash-cms/admin@1.0.1'
  - '@emdash-cms/auth@1.0.1'
  - '@emdash-cms/blocks@1.0.1'
  - '@emdash-cms/cloudflare@1.0.1'
  - '@emdash-cms/gutenberg-to-portable-text@1.0.1'
  - '@emdash-cms/plugin-cli@0.13.1'
  - '@emdash-cms/plugin-test@0.2.6'
  - emdash@1.0.1
